Пул реквест ДЗ переход на страницу восстановления профиля
TsakunovR/AT2-Sergey pull request #2
Opened 2023-12-11 18:18 UTC by Sergey-Konev-D1

Добавлен алюр, добавлен тест-кейс проверки перехода на страницу воостановления профиля, использование функции randrange

2023-12-13 07:49 UTC, TsakunovR requested changes

2023-12-13 07:49 UTC, TsakunovR commented on pages/PasswordRecovery.py
> +class LoginPageLocators:
измени название на более подходящее, например на PaswordRecoveryLocators

2023-12-13 07:49 UTC, TsakunovR commented on pages/PasswordRecovery.py
> +class LoginPageHelperPasswordRecovery(BasePage):
здесь аналогично прошлому комментарию, например PasswordRecoveryHelper

2023-12-18 10:12 UTC, Sergey-Konev-D1 commented
Исправил замечания по именованию классов + выполнил работу со выпадающим списком, переименованы классы и функции для более удобного чтения,написана фикстура для общего шага,создан новая страница ТК восстановления, созданы новые объекты pages написан тест для проверкаи кода выбранной страны. Аллюр отчет пока не прикручен к новым кейсам

2023-12-18 14:15 UTC, TsakunovR approved these changes

2023-12-18 14:15 UTC, merged